
[Nehemoth]
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Nehemoth Heath Multipler" = 1.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Nehemoth Ranged Damage" = 3.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Nehemoth Laser Damage" = 3.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Nehemoth Melee Damage Multipler" = 1.0

[Froglin]
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Froglin Heath Multipler" = 1.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Froglin Projetile Damage" = 7.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Froglin Melee Damage Multipler" = 1.0

[Bulldrogioth]
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Bulldrogioth Heath Multipler" = 1.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Bulldrogioth Melee Damage Multipler" = 1.0

[Cleric]
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Cleric Heath Multipler" = 1.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Cleric Projectile Damage" = 5.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Cleric Melee Damage Multipler" = 1.0

[SpawnRate]
	#Changed Cleric SpawnRate. [0 ~ 100]
	#Range: 0 ~ 100
	"Cleric SpawnRate" = 5
	#Changed Soulfire Nehemoth SpawnRate. [0 ~ 100]
	#Range: 0 ~ 100
	"SoulFire Nehemoth SpawnRate" = 1
	#Changed Nehemoth SpawnRate. [0 ~ 100]
	#Range: 0 ~ 100
	"Nehemoth SpawnRate" = 2
	#Changed Nehemoth SpawnRate in Fortress. [0 ~ 100]
	#Range: 0 ~ 100
	"Nehemoth SpawnRate in Fortress" = 1
	#Changed Bulldrogioth SpawnRate in Ocean Ruin. [0 ~ 100]
	#Range: 0 ~ 100
	"Bulldrogioth SpawnRate in Ocean Ruin" = 5
	#Changed Bulldrogioth SpawnRate. [0 ~ 100]
	#Range: 0 ~ 100
	"Bulldrogioth SpawnRate" = 5
	#Changed Froglin SpawnRate. [0 ~ 100]
	#Range: 0 ~ 100
	"Froglin SpawnRate" = 2

[spawnRoll]
	#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
	#Range: > 0
	"Cleric SpawnRoll" = 25
	#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
	#Range: > 0
	"Nehemoth SpawnRoll" = 15
	#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
	#Range: > 0
	"Bulldrogioth SpawnRoll" = 15
	#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
	#Range: > 0
	"Froglin SpawnRoll" = 8

[Equipment]
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Thirst For Blood Damage" = 8.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Thirst For Blood Laser Damage" = 9.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Sets Devil Splitter Damage" = 6.0
	#Range: > 1
	"Sets Diabolium Helmet Armor Value" = 3
	#Range: > 1
	"Sets Diabolium Chestplate Armor Value" = 8
	#Range: > 1
	"Sets Diabolium Leggings Armor Value" = 6
	#Range: > 1
	"Sets Diabolium Armor Durability" = 24
	#Range: > 1
	"Sets Crust Helmet Armor Value" = 4
	#Range: > 1
	"Sets Crust Chestplate Armor Value" = 9
	#Range: > 1
	"Sets Crust Leggings Armor Value" = 7
	#Range: > 1
	"Sets Crust Armor Durability" = 30
	#Range: > 1
	"Sets Plague Doctor Mask Armor Value" = 3
	#Range: > 1
	"Sets Plague Doctor Mask Durability" = 8

