
#Use this feature toggle section to easily choose Undermod features that you want to disable, without the need to alter the rest of the configuration. To disable a feature, just set it to 'false'.
#IMPORTANT:
#   - For now, changing Undermod configuration will affect ALL of your worlds.
#   - Changing Undermod configuration will most likely alter Undermod world generation, which can create hard seams and incomplete underbiomes between chunks with the old configuration and chunks
#     with the new configuration.
#   - It's recommended to make a backup of your world before changing the configuration, and also save the Undermod config file that you used to generate it.
#     This ensures seamless terrain generation can continue when you restore the world.
[feature_toggles]
	underbiome_forest = true
	underbiome_caverns = true
	underbiome_sewers = true
	#Note that if you disable rivers, sewers will still generate, but most will have a dead end without outfalls to underground bodies of water.
	underbiome_river = true
	underbiome_sea = true
	underbiome_crater = true
	entity_leech = true
	entity_rat = true
	#Heaps of filth blocks spawn leeches when underwater, and slimes when on dry ground. Disabling this won't prevent filth blocks generation, but it will stop any spwaning from them.
	spawning_filth_blocks = true

#--- Undermod World Generation Configuration ---
#
# There are three different types of Mystronics Underbiomes. Only Adaptive Underbiome generation is configurable for now:
#
# > GEOGRAPHICAL UNDERBIOMES
#     - Define large geographical features in Mystronics underground world. For example, underground seas and rivers.
#     - Configuration for geographical underbiomes is not yet implemented, but it will become available in a future Undermod version.
#
# > ADAPTIVE UNDERBIOMES
#     - Generation will attempt to comply with Minecraft surface conditions.
#       For example, if an adaptive underbiome is generated in a Minecraft forest, by default it will create a Mystronics underground
#       forest below it, or other underbiome compatible with a Minecraft forest.
#     - Different types of adaptive underbiomes have different surface requirements.
#     - Given that adaptive underbiomes cannot extend outside the area with required surface conditions, they won't generate if no
#       valid adaptive types exist for that area.
#     - Adaptive underbiome types for each Minecraft surface biome can be configured in this file.
#
# > CONSTRAINED UNDERBIOMES
#     - Generation is contingent upon different special conditions depending on the underbiome type.
#       For example, Sewers can only generate below villages, and connect to underground bodies of water and other villages.
#     - Configuration for constrained underbiomes is not yet implemented, but it will become available in a future Undermod version.
#
[general]
	#If you disable Adapt to Existing World, Undermod will generate underbiomes without adapting to previously existing chunks.
	#Disabling this option ensures that a seed always generates the same Undermod world for your surface world, regardless of whether you are creating a new world or loading
	#an existing one. However, if you load an existing world with this option disabled, it can result in hard seams and incomplete underbiomes where new terrain meets chunks
	#generated before installing Undermod (or chunks with different generation for surface biomes, or with different Undermod configuration that affects world generation results).
	#It's recommended to keep this option enabled unless you are confident in the outcome it will produce.
	adapt_to_existing_world = true
	# Generation of Adaptive Underbiomes stops when it reaches a surface biome kind where the underbiome is not allowed. However, biome
	# kinds listed under 'neutral_biome_kinds' will not stop underbiome generation. For example, the default configuration allows
	# underbiomes to cross under Minecraft rivers when the underbiome is allowed on the other side of the river, even if the underbiome
	# type does not generate in rivers.
	neutral_biome_kinds = ["river"]

[underbiome_density]
	# Adaptive Underbiomes Per Map: Average number of Adaptive Underbiomes to be generated per full Minecraft map (zoom level 4 map / 2028x2048 blocks).
	# Remember that this is just an average - underbiomes don't know about Minecraft maps and will cross from one map to another.
	# Also, some areas might have higher underbiome density to balance out lower density ones. Densities that are too high might cause lag.
	#Range: 0.016 ~ 100.0
	adaptiveUnderbiomesPerMap = 12.0
	# Crater Density Multiplier: Normally you can expect to find 1 crater for every 6 to 9 fully explored Minecraft maps.
	# Use this multiplier to change the number of craters by a factor. For example, if you use 1.5 you can expect to find
	# approximately 1 crater for every 4 to 6 fully explored Minecraft maps. With 0.5, expect 1 crater for every 13 to 18 maps. Bear in mind that this is an average - these frequencies are not guaranteed.
	#Range: 0.2 ~ 10.0
	craterDensityMultiplier = 1.0

# This section classifies vanilla or modded Minecraft biomes into 'Surface Biome Kinds', that Undermod uses to determine where it
# should generate Mystronics Underbiomes. If you want to add Adaptive Underbiomes under a new Minecraft biome, first add the Minecraft
# biome to a biome kind below. You can add it to several biome kinds if needed. You CANNOT remove or add new biome kinds, doing so will result in runtime errors.
[surface_biome_kinds]
	ocean = ["minecraft:ocean", "minecraft:deep_ocean", "minecraft:frozen_ocean", "minecraft:deep_frozen_ocean", "minecraft:cold_ocean", "minecraft:deep_cold_ocean", "minecraft:lukewarm_ocean", "minecraft:warm_ocean", "minecraft:deep_warm_ocean", "biomesoplenty:kelp_forest", "biomesoplenty:coral_reef", "byg:dead_sea", "byg:lush_stacks"]
	cold_forest = ["minecraft:taiga", "minecraft:taiga_hills", "minecraft:taiga_mountains", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:snowy_taiga_mountains", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:giant_spruce_taiga", "minecraft:giant_spruce_taiga_hills", "biomesoplenty:snowy_forest", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:boreal_forest", "biomesoplenty:maple_woods", "byg:cika_woods", "byg:borealis_grove", "byg:coniferous_forest", "byg:dacite_ridges", "byg:maple_taiga", "byg:autumnal_taiga", "byg:frosted_taiga", "byg:frosted_coniferous_forest"]
	temperate_forest = ["minecraft:forest", "minecraft:wooded_hills", "minecraft:birch_forest", "minecraft:birch_forest_hills", "minecraft:tall_birch_forest", "minecraft:tall_birch_hills", "minecraft:dark_forest", "minecraft:dark_forest_hills", "biomesoplenty:coniferous_forest", "biomesoplenty:eucalyptus_forest", "biomesoplenty:redwood_forest", "biomesoplenty:seasonal_forest", "biomesoplenty:temperate_rainforest", "biomesoplenty:maple_woods", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:bamboo_forest", "biomesoplenty:rainforest", "biomesoplenty:aspen_glade", "biomesoplenty:jacaranda_glade", "biomesoplenty:mediterranean_forest", "biomesoplenty:orchard", "biomesoplenty:pumpkin_patch", "biomesoplenty:woodland", "byg:aspen_forest", "byg:aspen_forest_hills", "byg:aspen_clearing", "byg:cherry_blossom_forest", "byg:ebony_woods", "byg:jacaranda_jungle", "byg:orchard", "byg:red_oak_forest", "byg:redwood_thicket", "byg:temperate_rainforest", "byg:canadian_shield", "byg:autumnal_forest", "byg:zelkova_forest", "byg:black_forest"]
	jungle = ["minecraft:jungle", "minecraft:jungle_hills", "minecraft:modified_jungle", "minecraft:bamboo_jungle", "minecraft:bamboo_jungle_hills", "biomesoplenty:tropical_rainforest", "byg:baobab_savanna", "byg:tropical_rainforest"]
	cold_plain = ["minecraft:snowy_tundra", "minecraft:ice_spikes", "biomesoplenty:cold_desert", "biomesoplenty:tundra", "biomesoplenty:snowy_tundra", "biomesoplenty:glacier", "byg:cardinal_tundra"]
	temperate_plain = ["minecraft:plains", "minecraft:sunflower_plains", "biomesoplenty:grassland", "biomesoplenty:prairie", "biomesoplenty:pasture", "biomesoplenty:meadow", "biomesoplenty:lavender_fields", "biomesoplenty:steppe", "biomesoplenty:shrubland", "byg:allium_shrubland", "byg:coconino_meadow", "byg:prairie", "byg:autumnal_valley", "byg:rose_fields", "byg:red_spruce_taiga", "byg:twilight_meadow"]
	hot_plain = ["minecraft:savanna", "biomesoplenty:brushland", "biomesoplenty:steppe", "biomesoplenty:shrubland", "biomesoplenty:lush_desert"]
	hot_desert = ["minecraft:desert", "minecraft:desert_hills", "minecraft:desert_lakes", "biomesoplenty:lush_desert", "biomesoplenty:oasis", "byg:mojave_desert"]
	badlands = ["minecraft:badlands"]
	mountain = ["minecraft:mountains", "minecraft:wooded_mountains", "minecraft:gravelly_mountains", "minecraft:modified_gravelly_mountains", "minecraft:shattered_savanna", "minecraft:shattered_savanna_plateau", "biomesoplenty:mountain", "biomesoplenty:alps", "biomesoplenty:crag", "byg:guiana_shield", "byg:guiana_clearing", "byg:guiana_springs", "byg:dacite_ridges", "byg:fragment_forest", "byg:howling_peaks"]
	magical = ["minecraft:dark_forest", "minecraft:dark_forest_hills", "minecraft:flower_forest", "biomesoplenty:bamboo_forest", "biomesoplenty:flower_island", "biomesoplenty:mystic_grove", "biomesoplenty:ominous_woods", "biomesoplenty:sacred_springs", "biomesoplenty:moor", "biomesoplenty:flower_field", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:lavender_fields", "byg:amaranth_fields", "byg:crag_gardens", "byg:ebony_woods", "byg:forgotten_forest", "byg:skyris_vale", "byg:weeping_witch_forest"]
	swamp = ["minecraft:swamp", "minecraft:swamp_hills", "biomesoplenty:lush_swamp", "biomesoplenty:dead_swamp", "biomesoplenty:moor", "biomesoplenty:marsh", "byg:bayou", "byg:cypress_swamplands", "byg:white_mangrove_marshes"]
	river = ["minecraft:river", "minecraft:frozen_river"]
	beach = ["minecraft:beach", "minecraft:stone_shore", "minecraft:snowy_beach", "biomesoplenty:gravel_beach", "biomesoplenty:white_beach", "biomesoplenty:origin_beach", "byg:rainbow_beach", "byg:tropical_islands", "byg:dacite_shore", "byg:basalt_barrera"]

# The following section specifies which Mystronics Underbiomes are generated in each surface biome kind defined in the 'surface_biome_kinds'
# section. It's used for Adaptive Underbiomes surface conditions, so if an adaptive underbiome type is not put under any biome kind, it
# will not generate at all. Some Explicit Underbiomes use this section as a recommendation too - that is, they might prioritize these
# biome kinds over others for generation, but will generate in other ones anyway when there is no other option nearby.
#
# Current underbiomes affected by this section are:
# [forest, caverns]
# IMPORTANT: Use only the underbiome names listed in the line above - any other keywords will result in an error.
[underbiomes_per_kind]
	ocean = []
	cold_forest = ["forest"]
	temperate_forest = ["forest"]
	jungle = ["forest", "caverns"]
	cold_plain = ["caverns"]
	temperate_plain = ["caverns"]
	hot_plain = ["caverns"]
	hot_desert = []
	badlands = ["caverns"]
	mountain = ["caverns"]
	magical = []
	swamp = []
	river = []
	beach = ["caverns"]

